import { articles } from './content.js';
const $=s=>document.querySelector(s);
const categories=[
 {key:'writing',name:'文章',en:'WRITING',title:'Field notes.',description:'认真记录，让思考有迹可循。',image:'assets/summer-notes.png',sub:'NOTES & ESSAYS'},
 {key:'projects',name:'项目',en:'PROJECTS',title:'Projects.',description:'把想法做出来，在实践中验证。',image:'assets/summer-projects.png',sub:'DEMOS & WEBSITES'},
 {key:'github',name:'GitHub',en:'OPEN SOURCE',title:'Open source.',description:'保持开放，让经验被复用。',image:'assets/summer-connection.png',sub:'CODE & REPOSITORIES'},
 {key:'contact',name:'联系',en:'CONTACT',title:'Say hello.',description:'真诚交流，一起把事情做好。',image:'assets/summer-connection.png',sub:'IDEAS & CONVERSATIONS'}
];
const items={
 writing:articles.map((a,i)=>({title:a[0],tag:'示例文章',glyph:['Aa','01','—','*'][i],description:['原型与产品验证：从小处开始，用真实反馈决定下一步。','AI 产品设计：把必要的选择和清楚的依据留给用户。','信息与视觉设计：在取舍中，让重要的内容被看见。','项目实践：为好奇心留一点空间。'][i],paragraphs:a.slice(1)})),
 projects:[{title:'Still · 专注计时器',tag:'HTML DEMO',glyph:'25:00',description:'25 分钟专注计时，支持暂停与重置。',href:'demo.html',cta:'进入 Demo'}, {title:'Field Notes · 数字花园',tag:'示例项目',glyph:'Fn',description:'一个持续记录与整理想法的项目展示位。',paragraphs:['这里用于展示已上线的项目，可配置项目简介与外部链接。'],pending:'项目网址待补充，当前为展示示例。'}],
 github:[{title:'personal-space',tag:'示例仓库',glyph:'</>',description:'个人网站源码与设计实践。',paragraphs:['这里用于介绍个人网站的源码结构、实现思路与使用方式。'],pending:'真实仓库地址待补充。'}, {title:'tiny-experiments',tag:'示例仓库',glyph:'{ }',description:'把交互想法做成可运行的小实验。',paragraphs:['这里用于收录 JavaScript 交互实验、可复用代码和实践记录。'],pending:'真实仓库地址待补充。'}, {title:'product-notes',tag:'示例仓库',glyph:'Aa',description:'整理产品观察与实践中的方法。',paragraphs:['这里用于展示可以公开复用的产品笔记与方法记录。'],pending:'真实仓库地址待补充。'}, {title:'interface-studies',tag:'示例仓库',glyph:'↗',description:'记录界面设计与交互实现的探索。',paragraphs:['这里用于展示界面组件、交互动效和实现说明。'],pending:'真实仓库地址待补充。'}],
 contact:[{title:'交流想法',tag:'产品 · 设计 · AI',glyph:'Hi.',description:'欢迎交流产品思考、设计实践与合作机会。',paragraphs:['我是王铭璐。想清楚，然后一直走。','希望在具体的问题和实践中，遇见可以一起把事情做好的人。'],pending:'邮箱与微信待补充。'}, {title:'一起做点什么',tag:'合作交流',glyph:'&',description:'从一个具体的问题开始，一起把想法做出来。',paragraphs:['如果你正在探索一个产品方向，或者需要交流原型和设计思路，欢迎联系。'],pending:'联系方式待补充。'}]
};
let selected=0,view='home',dragState=null,suppressClickUntil=0;
let wheelSum=0,lastWheelTime=0,lastWheelSwitch=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let motion=!reduced.matches;
const node=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e};
function setMotion(enabled){motion=enabled;document.body.classList.toggle('motion-off',!enabled);$('#motion-toggle').setAttribute('aria-pressed',String(!enabled));$('#motion-toggle').setAttribute('aria-label',enabled?'暂停动效':'启用动效');$('#motion-toggle').textContent=enabled?'Ⅱ':'▷'}
$('#motion-toggle').onclick=()=>setMotion(!motion);reduced.addEventListener('change',e=>setMotion(!e.matches));setMotion(motion);
categories.forEach((c,i)=>{
 const nav=node('button','',c.name);nav.dataset.category=i;nav.setAttribute('aria-label',c.name+'分类');nav.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')select(i)});nav.addEventListener('focus',()=>select(i));nav.onclick=()=>select(i);$('#categories').append(nav);
 const album=node('button','album');album.style.setProperty('--i',i);album.dataset.album=i;
 album.innerHTML=`<span class="album-inner"><span class="cover cover-${c.key}"><span class="cover-top"><span>${c.en}</span><span>0${i+1}</span></span><span class="cover-title">${c.title}</span><span class="cover-art"><img src="${c.image}" alt="" draggable="false"><span class="cover-number">0${i+1}</span></span><span class="cover-bottom"><strong>${c.name}</strong><small>SELECT</small></span></span></span>`;
 $('#albums').append(album);
});
function select(i,hash=true){selected=(i+4)%4;const c=categories[selected];document.querySelectorAll('[data-category]').forEach((b,j)=>{b.classList.toggle('active',j===selected);b.setAttribute('aria-pressed',String(j===selected))});document.querySelectorAll('.album').forEach((a,j)=>{let d=j-selected;if(d>2)d-=4;if(d< -1)d+=4;const narrow=innerWidth<761;const x=d*(narrow?142:225)+(dragState?.offset||0);a.style.setProperty('--x',x+'px');a.style.setProperty('--y',Math.abs(d)*12+'px');a.style.setProperty('--ry',d===0?'0deg':(-Math.sign(d)*30)+'deg');a.style.setProperty('--rz',d*3+'deg');a.style.setProperty('--s',1-Math.abs(d)*.12);a.style.setProperty('--z',10-Math.abs(d));a.style.setProperty('--brightness',j===selected?'1':'.83');a.setAttribute('aria-label',categories[j].name+'，点击展开');a.setAttribute('aria-pressed',String(j===selected));});$('#large-index').textContent='0'+(selected+1);$('#selection-en').textContent=c.en;$('#selection-name').textContent=c.name;$('#category-description').textContent=c.description;if(hash&&view==='home')history.replaceState(null,'','#'+c.key)}
function openDeck(){view='deck';const c=categories[selected];$('#home-view').hidden=true;$('#deck-view').hidden=false;$('#deck-en').textContent=c.en;$('#deck-title').textContent=c.name;$('#deck-description').textContent=c.description;$('#deck-count').textContent=String(items[c.key].length).padStart(2,'0')+' ITEMS'+(c.key==='contact'?'':' / 示例内容');$('#deck-hint').textContent='点击卡片旋转 · 再点击进入';$('#deck-row').replaceChildren();items[c.key].forEach((item,i)=>{
 const wrapper=node('div','content-card');wrapper.style.setProperty('--i',i);const button=node('button','content-card-button');button.setAttribute('aria-label',item.title+'，点击旋转查看');button.setAttribute('aria-pressed','false');const flipper=node('span','card-flipper');const front=node('span','card-front');const kicker=node('span','card-kicker');kicker.append(node('span','',c.en),node('span','','0'+(i+1)));const art=node('span','card-illustration');const img=node('img');img.src=c.image;img.alt='';img.draggable=false;img.style.objectPosition='50% '+(35+i*12)+'%';art.append(img,node('span','card-glyph',item.glyph));front.append(kicker,art,node('h2','',item.title));const foot=node('span','card-foot');foot.append(node('span','',item.tag),node('span','','点击旋转 ↻'));front.append(foot);const back=node('span','card-back');back.setAttribute('aria-hidden','true');back.append(node('span','card-kicker',item.tag),node('h2','',item.title),node('p','',item.description),node('span','card-enter',(item.cta||'进入详情')+' ↗'));flipper.append(front,back);button.append(flipper);const reset=node('button','flip-reset','↶');reset.setAttribute('aria-label','翻回 '+item.title);reset.tabIndex=-1;
 let flipped=false,unlockAt=0;
 function flip(value){flipped=value;wrapper.classList.toggle('flipped',value);front.setAttribute('aria-hidden',String(value));back.setAttribute('aria-hidden',String(!value));button.setAttribute('aria-pressed',String(value));button.setAttribute('aria-label',item.title+(value?'，再次点击进入':'，点击旋转查看'));reset.tabIndex=value?0:-1;unlockAt=performance.now()+(motion?760:0);$('#deck-hint').textContent=value?'再次点击卡片进入 · 右上角可翻回':'点击卡片旋转 · 再点击进入'}
 button.onclick=()=>{if(performance.now()<unlockAt)return;if(!flipped){flip(true);return}if(item.href){location.href=item.href;return}openItem(item,c)};reset.onclick=()=>{flip(false);button.focus()};wrapper.append(button,reset);$('#deck-row').append(wrapper)
 });$('.deck-scroll').scrollLeft=0;history.replaceState(null,'','#'+c.key+'/cards');$('#back-home').focus({preventScroll:true});updateScrollButtons();}
function goHome(){view='home';$('#deck-view').hidden=true;$('#home-view').hidden=false;select(selected);document.querySelector('[data-category="'+selected+'"]').focus({preventScroll:true})}
$('#back-home').onclick=goHome;
function openItem(item,c){$('#reader-label').textContent=c.en+' / '+item.tag;$('#reader-title').textContent=item.title;$('#reader-body').replaceChildren(...(item.paragraphs||[item.description]).map(p=>node('p','',p)));if(item.pending)$('#reader-body').append(node('p','detail-note',item.pending));$('#reader').showModal()}
$('.reader-close').onclick=()=>$('#reader').close();$('#reader').addEventListener('click',e=>{if(e.target!==$('#reader'))return;const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()});
function updateScrollButtons(){const s=$('.deck-scroll');$('#deck-prev').disabled=s.scrollLeft<2;$('#deck-next').disabled=s.scrollLeft+s.clientWidth>=s.scrollWidth-2}
$('.deck-scroll').addEventListener('scroll',updateScrollButtons);$('#deck-prev').onclick=()=>$('.deck-scroll').scrollBy({left:-305,behavior:motion?'smooth':'instant'});$('#deck-next').onclick=()=>$('.deck-scroll').scrollBy({left:305,behavior:motion?'smooth':'instant'});
function fromHash(){const [key,part]=location.hash.slice(1).split('/');const i=categories.findIndex(c=>c.key===key);selected=i<0?0:i;select(selected,false);if(part==='cards')openDeck();else{view='home';$('#home-view').hidden=false;$('#deck-view').hidden=true}}
window.addEventListener('hashchange',fromHash);window.addEventListener('resize',()=>{select(selected,false);updateScrollButtons()});document.addEventListener('keydown',e=>{if($('#reader').open||e.metaKey||e.ctrlKey||e.altKey)return;if(e.key==='Escape'&&view==='deck'){goHome();return}if(view==='home'&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();select(selected+(e.key==='ArrowRight'?1:-1));document.querySelector('[data-category="'+selected+'"]').focus()}});fromHash();

// Category browsing: stable label hover, deliberate drag/swipe and wheel only.
const stage=$('#albums');
stage.addEventListener('click',e=>{if(view!=='home'||performance.now()<suppressClickUntil)return;const x=e.clientX,y=e.clientY;const candidates=[...stage.querySelectorAll('.album')].map((album,i)=>{const r=album.getBoundingClientRect(),label=album.querySelector('.cover-bottom strong').getBoundingClientRect();return{i,r,d:(x-(label.left+label.right)/2)**2+.15*(y-(label.top+label.bottom)/2)**2}}).filter(({r})=>x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom).sort((a,b)=>a.d-b.d);const keyboardAlbum=e.detail===0?e.target.closest('.album'):null;const targetIndex=keyboardAlbum?Number(keyboardAlbum.dataset.album):candidates[0]?.i;if(targetIndex===undefined)return;e.preventDefault();if(targetIndex===selected)openDeck();else select(targetIndex)},true);
stage.addEventListener('pointerdown',e=>{if(e.button!==0||view!=='home')return;dragState={id:e.pointerId,x:e.clientX,y:e.clientY,offset:0,dragging:false};});
stage.addEventListener('pointermove',e=>{if(!dragState||dragState.id!==e.pointerId)return;const dx=e.clientX-dragState.x,dy=e.clientY-dragState.y;if(!dragState.dragging){if(Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>12){dragState=null;return}if(Math.abs(dx)<12)return;dragState.dragging=true;stage.setPointerCapture(e.pointerId);stage.classList.add('is-dragging')}dragState.offset=Math.max(-180,Math.min(180,dx*.65));select(selected,false)});
function releaseSwipe(e){if(!dragState||e.pointerId!==dragState.id)return;const d=dragState;dragState=null;stage.classList.remove('is-dragging');if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId);if(d.dragging){suppressClickUntil=performance.now()+450;select(selected+(e.type==='pointercancel'||Math.abs(d.offset)<35?0:d.offset<0?1:-1))}else select(selected,false)}
stage.addEventListener('pointerup',releaseSwipe);stage.addEventListener('pointercancel',releaseSwipe);stage.addEventListener('lostpointercapture',()=>{if(dragState){dragState=null;stage.classList.remove('is-dragging');select(selected,false)}});stage.addEventListener('dragstart',e=>e.preventDefault());
stage.addEventListener('wheel',e=>{if(view!=='home'||e.ctrlKey||Math.abs(e.deltaX)<=Math.abs(e.deltaY))return;const now=performance.now(),delta=e.deltaX*(e.deltaMode===1?16:e.deltaMode===2?innerWidth:1);if(Math.abs(delta)<2)return;e.preventDefault();if(now-lastWheelTime>200)wheelSum=0;lastWheelTime=now;if(now-lastWheelSwitch<650)return;wheelSum+=delta;if(Math.abs(wheelSum)>65){select(selected+(wheelSum>0?1:-1));wheelSum=0;lastWheelSwitch=now}},{passive:false});
